server:
  port: 8086

spring:
  application:
    name: rabbitmq-demo
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

#  guest用户只适用于 rabbitmq服务同台机器运行项目访问
  rabbitmq:
    host: 120.78.78.162
    port: 5672
    username: admin
    password: admin123
    virtual-host: luoyj

# swagger配置
swagger:
  enabled: true
  title: RabbitMQ
  description: "RabbitMQ 接口"
  version: 1.0
  base-package: com.yonjar.demo #包名